export const PUBLIC_LAYOUT = "default";

export const SIDEBAR_ITEMS = [
    {
        name: "Home",
        icon: "fas fa-home",
        path: "/",
    },
    {
        name: "Faculties",
        icon: "fas fa-university",
        path: "/faculties",
    },
    {
        name: "Teachers",
        icon: "fas fa-chalkboard-teacher",
        path: "/teachers",
    },
    {
        name: "Change password",
        icon: "fas fa-key",
        path: "/change-password",
    },
    {
        name: "Add user",
        icon: "fas fa-user-plus",
        path: "/register",
    },
    {
        name: "About",
        icon: "fas fa-info-circle",
        path: "/about",
    },
];

export const LIST_ICONS_POST = [
    {
        name: "Tag",
        icon: "fas fa-tags text-blue-600",
        other: "",
    },
    {
        name: "Location",
        icon: "fas fa-location-arrow text-green-600",
        other: "",
    },
    {
        name: "Feeling",
        icon: "fas fa-smile-beam text-yellow-600",
        other: "",
    },
];

export const LIST_NOTIFICATIONS_SAMPLE = [
    {
        id: 0,
        title: "Schedule for professional skills Exam in August 2021",
        path: "/notification-detail/notification-0",
        createdAt: 1630472007139,
        faculty: "Faculty of Electrical & Electronics Engineering",
        isOwner: true,
        status: false,
    },
    {
        id: 1,
        title: "Exam schedule for subject repayment class - phase August, 2021",
        path: "/notification-detail/notification-1",
        createdAt: 1630472007147,
        faculty: "Faculty of Pharmacy",
        isOwner: false,
        status: false,
    },
    {
        id: 2,
        title: "Exam schedule for subject repayment class - phase August, 2021",
        path: "/notification-detail/notification-2",
        createdAt: 1630472007147,
        faculty: "Faculty of Information Technology",
        isOwner: true,
        status: false,
    },
    {
        id: 3,
        title: "Exam schedule for subject repayment class - phase August, 2021",
        path: "/notification-detail/notification-3",
        createdAt: 1630472007148,
        faculty: "College of International Studies",
        isOwner: false,
        status: true,
    },
    {
        id: 4,
        title: "[Official] Graduation exam schedule for basic and specialized courses, phase August,2021",
        path: "/notification-detail/notification-4",
        createdAt: 1630472007149,
        faculty: "Faculty of Electrical & Electronics Engineering",
        isOwner: false,
        status: true,
    },
    {
        id: 5,
        title: "Exam schedule for subject repayment class - phase August, 2021",
        path: "/notification-detail/notification-5",
        createdAt: 1630472007149,
        faculty: "Faculty of Pharmacy",
        isOwner: false,
        status: true,
    },
    {
        id: 6,
        title: "Exam schedule for subject repayment class - phase August, 2021",
        path: "/notification-detail/notification-6",
        createdAt: 1630472007150,
        faculty: " Faculty of Information Technology",
        isOwner: false,
        status: true,
    },
    {
        id: 7,
        title: "Exam schedule for subject repayment class - phase August, 2021",
        path: "/notification-detail/notification-7",
        createdAt: 1630472007151,
        faculty: " Faculty of Information Technology",
        isOwner: false,
        status: false,
    },
    {
        id: 8,
        title: "Online exam schedule for semester 2/ 2020-2021 (Final-term phase 2)",
        path: "/notification-detail/notification-8",
        createdAt: 1630472007151,
        faculty: "Faculty of Pharmacy",
        isOwner: false,
        status: true,
    },
    {
        id: 9,
        title: "[Official] Graduation exam schedule for basic and specialized courses, phase August,2021",
        path: "/notification-detail/notification-9",
        createdAt: 1630472007152,
        faculty: "Faculty of Pharmacy",
        isOwner: false,
        status: false,
    },
    {
        id: 10,
        title: "Exam schedule for subject repayment class - phase August, 2021",
        path: "/notification-detail/notification-10",
        createdAt: 1630472007152,
        faculty: "Faculty of Pharmacy",
        isOwner: false,
        status: false,
    },
    {
        id: 11,
        title: "Online exam schedule for semester 2/ 2020-2021 (Final-term phase 2)",
        path: "/notification-detail/notification-11",
        createdAt: 1630472007153,
        faculty: "College of International Studies",
        isOwner: false,
        status: true,
    },
    {
        id: 12,
        title: "[Official] Graduation exam schedule for basic and specialized courses, phase August,2021",
        path: "/notification-detail/notification-12",
        createdAt: 1630472007154,
        faculty: " Faculty of Information Technology",
        isOwner: false,
        status: false,
    },
    {
        id: 13,
        title: "Online exam schedule for semester 2/ 2020-2021 (Final-term phase 2)",
        path: "/notification-detail/notification-13",
        createdAt: 1630472007155,
        faculty: " Faculty of Information Technology",
        isOwner: false,
        status: false,
    },
    {
        id: 14,
        title: "Exam schedule for subject repayment class - phase August, 2021",
        path: "/notification-detail/notification-14",
        createdAt: 1630472007156,
        faculty: " Faculty of Information Technology",
        isOwner: false,
        status: false,
    },
    {
        id: 15,
        title: "Online exam schedule for semester 2/ 2020-2021 (Final-term phase 2)",
        path: "/notification-detail/notification-15",
        createdAt: 1630472007158,
        faculty: "Faculty of Electrical & Electronics Engineering",
        isOwner: false,
        status: true,
    },
    {
        id: 16,
        title: "Schedule for professional skills Exam in August 2021",
        path: "/notification-detail/notification-16",
        createdAt: 1630472007158,
        faculty: "Faculty of Electrical & Electronics Engineering",
        isOwner: false,
        status: false,
    },
    {
        id: 17,
        title: "Exam schedule for subject repayment class - phase August, 2021",
        path: "/notification-detail/notification-17",
        createdAt: 1630472007159,
        faculty: " Faculty of Information Technology",
        isOwner: false,
        status: true,
    },
    {
        id: 18,
        title: "Online exam schedule for semester 2/ 2020-2021 (Final-term phase 2)",
        path: "/notification-detail/notification-18",
        createdAt: 1630472007160,
        faculty: "Faculty of Pharmacy",
        isOwner: false,
        status: true,
    },
    {
        id: 19,
        title: "Exam schedule for subject repayment class - phase August, 2021",
        path: "/notification-detail/notification-19",
        createdAt: 1630472007161,
        faculty: "Faculty of Pharmacy",
        isOwner: false,
        status: true,
    },
    {
        id: 20,
        title: "Schedule for professional skills Exam in August 2021",
        path: "/notification-detail/notification-20",
        createdAt: 1630472007161,
        faculty: "Faculty of Electrical & Electronics Engineering",
        isOwner: false,
        status: true,
    },
    {
        id: 21,
        title: "Schedule for professional skills Exam in August 2021",
        path: "/notification-detail/notification-21",
        createdAt: 1630472007162,
        faculty: " Faculty of Information Technology",
        isOwner: false,
        status: true,
    },
    {
        id: 22,
        title: "Online exam schedule for semester 2/ 2020-2021 (Final-term phase 2)",
        path: "/notification-detail/notification-22",
        createdAt: 1630472007163,
        faculty: "Faculty of Pharmacy",
        isOwner: false,
        status: true,
    },
    {
        id: 23,
        title: "Exam schedule for subject repayment class - phase August, 2021",
        path: "/notification-detail/notification-23",
        createdAt: 1630472007163,
        faculty: "Faculty of Pharmacy",
        isOwner: false,
        status: false,
    },
    {
        id: 24,
        title: "[Official] Graduation exam schedule for basic and specialized courses, phase August,2021",
        path: "/notification-detail/notification-24",
        createdAt: 1630472007164,
        faculty: "Faculty of Pharmacy",
        isOwner: false,
        status: true,
    },
    {
        id: 25,
        title: "[Official] Graduation exam schedule for basic and specialized courses, phase August,2021",
        path: "/notification-detail/notification-25",
        createdAt: 1630472007165,
        faculty: "Faculty of Electrical & Electronics Engineering",
        isOwner: false,
        status: false,
    },
    {
        id: 26,
        title: "Schedule for professional skills Exam in August 2021",
        path: "/notification-detail/notification-26",
        createdAt: 1630472007165,
        faculty: "Faculty of Electrical & Electronics Engineering",
        isOwner: false,
        status: false,
    },
    {
        id: 27,
        title: "Schedule for professional skills Exam in August 2021",
        path: "/notification-detail/notification-27",
        createdAt: 1630472007166,
        faculty: " Faculty of Information Technology",
        isOwner: false,
        status: true,
    },
    {
        id: 28,
        title: "[Official] Graduation exam schedule for basic and specialized courses, phase August,2021",
        path: "/notification-detail/notification-28",
        createdAt: 1630472007166,
        faculty: " Faculty of Information Technology",
        isOwner: false,
        status: true,
    },
    {
        id: 29,
        title: "[Official] Graduation exam schedule for basic and specialized courses, phase August,2021",
        path: "/notification-detail/notification-29",
        createdAt: 1630472007167,
        faculty: "Faculty of Electrical & Electronics Engineering",
        isOwner: false,
        status: false,
    },
    {
        id: 30,
        title: "Schedule for professional skills Exam in August 2021",
        path: "/notification-detail/notification-30",
        createdAt: 1630472007167,
        faculty: "Faculty of Pharmacy",
        isOwner: false,
        status: true,
    },
    {
        id: 31,
        title: "[Official] Graduation exam schedule for basic and specialized courses, phase August,2021",
        path: "/notification-detail/notification-31",
        createdAt: 1630472007168,
        faculty: "Faculty of Pharmacy",
        isOwner: false,
        status: true,
    },
    {
        id: 32,
        title: "[Official] Graduation exam schedule for basic and specialized courses, phase August,2021",
        path: "/notification-detail/notification-32",
        createdAt: 1630472007168,
        faculty: "Faculty of Pharmacy",
        isOwner: false,
        status: true,
    },
    {
        id: 33,
        title: "Exam schedule for subject repayment class - phase August, 2021",
        path: "/notification-detail/notification-33",
        createdAt: 1630472007169,
        faculty: " Faculty of Information Technology",
        isOwner: false,
        status: false,
    },
    {
        id: 34,
        title: "Schedule for professional skills Exam in August 2021",
        path: "/notification-detail/notification-34",
        createdAt: 1630472007170,
        faculty: " Faculty of Information Technology",
        isOwner: false,
        status: true,
    },
    {
        id: 35,
        title: "[Official] Graduation exam schedule for basic and specialized courses, phase August,2021",
        path: "/notification-detail/notification-35",
        createdAt: 1630472007171,
        faculty: "Faculty of Pharmacy",
        isOwner: false,
        status: true,
    },
    {
        id: 36,
        title: "Exam schedule for subject repayment class - phase August, 2021",
        path: "/notification-detail/notification-36",
        createdAt: 1630472007173,
        faculty: "Faculty of Pharmacy",
        isOwner: false,
        status: true,
    },
    {
        id: 37,
        title: "Online exam schedule for semester 2/ 2020-2021 (Final-term phase 2)",
        path: "/notification-detail/notification-37",
        createdAt: 1630472007173,
        faculty: " Faculty of Information Technology",
        isOwner: false,
        status: false,
    },
    {
        id: 38,
        title: "[Official] Graduation exam schedule for basic and specialized courses, phase August,2021",
        path: "/notification-detail/notification-38",
        createdAt: 1630472007174,
        faculty: "Faculty of Pharmacy",
        isOwner: false,
        status: false,
    },
    {
        id: 39,
        title: "[Official] Graduation exam schedule for basic and specialized courses, phase August,2021",
        path: "/notification-detail/notification-39",
        createdAt: 1630472007174,
        faculty: " Faculty of Information Technology",
        isOwner: false,
        status: true,
    },
    {
        id: 40,
        title: "Online exam schedule for semester 2/ 2020-2021 (Final-term phase 2)",
        path: "/notification-detail/notification-40",
        createdAt: 1630472007175,
        faculty: " Faculty of Information Technology",
        isOwner: false,
        status: true,
    },
    {
        id: 41,
        title: "[Official] Graduation exam schedule for basic and specialized courses, phase August,2021",
        path: "/notification-detail/notification-41",
        createdAt: 1630472007175,
        faculty: " Faculty of Information Technology",
        isOwner: false,
        status: false,
    },
    {
        id: 42,
        title: "Schedule for professional skills Exam in August 2021",
        path: "/notification-detail/notification-42",
        createdAt: 1630472007176,
        faculty: "College of International Studies",
        isOwner: false,
        status: true,
    },
    {
        id: 43,
        title: "Online exam schedule for semester 2/ 2020-2021 (Final-term phase 2)",
        path: "/notification-detail/notification-43",
        createdAt: 1630472007177,
        faculty: "Faculty of Electrical & Electronics Engineering",
        isOwner: false,
        status: false,
    },
    {
        id: 44,
        title: "Online exam schedule for semester 2/ 2020-2021 (Final-term phase 2)",
        path: "/notification-detail/notification-44",
        createdAt: 1630472007177,
        faculty: " Faculty of Information Technology",
        isOwner: false,
        status: true,
    },
];

export const LIST_FACULTIES_SAMPLE = [
    {
        id: 0,
        title: "Faculty of Information Technology",
        path: "/faculty-0",
        img: "programmer_imem.svg",
    },
    {
        id: 1,
        title: "Faculty of Pharmacy",
        path: "/faculty-1",
        img: "medicine.svg",
    },
    {
        id: 2,
        title: "Faculty of Electrical & Electronics Engineering",
        path: "/faculty-2",
        img: "Electronics.svg",
    },
    {
        id: 3,
        title: "College of International Studies",
        path: "/faculty-3",
        img: "International.svg",
    },
    {
        id: 4,
        title: "Faculty of Accounting",
        path: "/faculty-4",
        img: "Accounting.svg",
    },
    {
        id: 5,
        title: "Faculty of Sports Science",
        path: "/faculty-5",
        img: "Sports.svg",
    },
    {
        id: 6,
        title: "Faculty of Applied Sciences",
        path: "/faculty-6",
        img: "science.svg",
    },
    {
        id: 7,
        title: "Faculty of Social Sciences & Humanities",
        path: "/faculty-7",
        img: "Humanities.svg",
    },
    {
        id: 8,
        title: "Faculty of Civil Engineering",
        path: "/faculty-8",
        img: "Building.svg",
    },
    {
        id: 9,
        title: "Faculty of Labor Relations and Trade Unions",
        path: "/faculty-9",
        img: "Labor_trade.svg",
    },
    {
        id: 10,
        title: "Faculty of Law",
        path: "/faculty-10",
        img: "law.svg",
    },
    {
        id: 11,
        title: "Faculty of Environment and Labour Safety",
        path: "/faculty-11",
        img: "Environmental_study.svg",
    },
    {
        id: 12,
        title: "Faculty of Industrial Fine Arts",
        path: "/faculty-12",
        img: "arts.svg",
    },
    {
        id: 13,
        title: "Faculty of Foreign Languages",
        path: "/faculty-13",
        img: "foriegn_language.svg",
    },
    {
        id: 14,
        title: "Faculty of Business Administration",
        path: "/faculty-14",
        img: "Business.svg",
    },
    {
        id: 15,
        title: "Faculty of Finance and Banking",
        path: "/faculty-15",
        img: "Finance.svg",
    },
    {
        id: 16,
        title: "Faculty of Mathematics & Statistics",
        path: "/faculty-16",
        img: "Statistics.svg",
    },
];

export const POSTS_SAMPLE = [
    {
        id: 1,
        username: "Ca Bien",
        faculty: null,
        title: "This is first post !",
        img: "pexels-eberhard-grossgasteiger-2098428.jpg",
        liked: 10,
        comments: [
            {
                id_user: 1,
                owner: "Cabien",
                content: "Adu cai gi do.",
                currentUser: true,
            },
            {
                id_user: 2,
                owner: "Nguyen Van A",
                content: "Hay the nho !",
                currentUser: false,
            },
            {
                id_user: 3,
                owner: "Nguyen Van B",
                content:
                    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam repellat labore voluptas vitae facere fugiat.",
                currentUser: false,
            },
            {
                id_user: 4,
                owner: "Nguyen Thi C",
                content:
                    "Lorem ipsum dolor sit amet consectetur adipisicing elit",
                currentUser: false,
            },
        ],
        currentUser: true,
    },
    {
        id: 2,
        username: "Nguyen Van A",
        faculty: null,
        title: "This is first post of A !",
        img: "post.jpg",
        liked: 20,
        comments: [
            {
                id_user: 1,
                owner: "Cabien",
                content: "Adu cai gi do.",
                currentUser: false,
            },
            {
                id_user: 2,
                owner: "Nguyen Van A",
                content: "Hay the nho !",
                currentUser: true,
            },
            {
                id_user: 3,
                owner: "Nguyen Van B",
                content:
                    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam repellat labore voluptas vitae facere fugiat.",
                currentUser: false,
            },
            {
                id_user: 4,
                owner: "Nguyen Thi C",
                content:
                    "Lorem ipsum dolor sit amet consectetur adipisicing elit",
                currentUser: false,
            },
        ],
        currentUser: false,
    },
    {
        id: 3,
        username: "Nguyen Van B",
        faculty: "Faculty of Information Technology",
        title: "This is first post of faculty !",
        img: "pexels-eberhard-grossgasteiger-2098428.jpg",
        liked: 30,
        comments: [
            {
                id_user: 1,
                owner: "Cabien",
                content: "Adu cai gi do.",
                currentUser: false,
            },
            {
                id_user: 2,
                owner: "Nguyen Van A",
                content: "Hay the nho !",
                currentUser: false,
            },
            {
                id_user: 3,
                owner: "Nguyen Van B",
                content:
                    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam repellat labore voluptas vitae facere fugiat.",
                currentUser: true,
            },
            {
                id_user: 4,
                owner: "Nguyen Thi C",
                content:
                    "Lorem ipsum dolor sit amet consectetur adipisicing elit",
                currentUser: false,
            },
        ],
        currentUser: false,
    },
];
